# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fiveMin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Then'
  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'Firebase/Database'
  # Pods for fiveMin

end
